name:                coconut-crack
version:             1.0
github:              "tpoomlmly/coconut-crack"
license:             MIT
author:              "Tommy Poll"
maintainer:          "tommy@poolle.co.uk"
copyright:           "Tommy Poll"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tpoomlmly/coconut-crack#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  coconut-crack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coconut-crack
    - optparse-applicative
